platform:
  - x86
  - x64
environment:
  matrix:
    - RUST_VERSION: stable
      BUILD_TARGET: msvc
    - RUST_VERSION: stable
      BUILD_TARGET: gnu
    - RUST_VERSION: beta
      BUILD_TARGET: msvc
    - RUST_VERSION: beta
      BUILD_TARGET: gnu
    - RUST_VERSION: nightly
      BUILD_TARGET: msvc
    - RUST_VERSION: nightly
      BUILD_TARGET: gnu
matrix:
  allow_failures:
    - BUILD_TARGET: msvc
      platform: x86
    - RUST_VERSION: nightly
cache:
  - target\debug\build
  - target\debug\deps
  - '%USERPROFILE%\.cargo'
install:
  - ps: |
        $env:PATH += ";C:\rust\bin";
        if ($env:platform -eq 'x86') {
          $arch_expanded = "i686-pc-windows-${env:BUILD_TARGET}";
          $env:ARCH = "x86";
          $env:bits = "32";
        } else {
          $arch_expanded = "x86_64-pc-windows-${env:BUILD_TARGET}";
          $env:ARCH = "amd64";
          $env:bits ="64";
        }
        if ($env:BUILD_TARGET -eq 'gnu') {
          $env:PATH += ";C:\msys64\mingw${env:bits}\bin";
          gcc --version;
        }
        if ($env:RUST_VERSION -eq 'stable') {
          echo "Downloading $channel channel manifest";
          $manifest = "${env:Temp}\channel-rust-stable";
          Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-stable" -FileName "$manifest";

          # Search the manifest lines for the correct filename based on expanded arch
          $match = Get-Content "$manifest" | Select-String -pattern "${arch_expanded}.exe" -simplematch;
          if (!$match -or !$match.line) {
            throw "Could not find ${arch_expanded} in stable channel manifest";
          }

          $env:rust_installer = $match.line;
        } else {
          $env:rust_installer = "rust-${env:RUST_VERSION}-${arch_expanded}.exe";
        }
  - curl --show-error --location --retry 5 --output rust-installer.exe https://static.rust-lang.org/dist/%rust_installer%
  - .\rust-installer.exe /VERYSILENT /NORESTART /DIR="C:\rust"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - cargo test --verbose --no-default-features
